### ISSUE TITLE
Need Java implementations for these topics

### ISSUE THREAD

**Issue by VamsiSangam** [VamsiSangam/theoryofprogramming#2]
Need Java implementations for -
* Bellman-Ford algorithm 
* Breadth First Search ✔️
* Depth First Search ✔️
* Dijkstra's Algorithm
* Prim's Algorithm
* Snakes and Ladders Game
* Binary Search algorithm ✔️
* Jump Search algorithm ✔️
* Merge Sort algorithm ✔️
* Quick Sort algorithm ✔️
* Segment Tree
* Trie Tree

Please create a separate pull request for each implementation contribution.

Implementing few topics are tough, the rest are easy. If you are a beginner, feel free to choose the easy ones. Please make sure your implementation is somewhat similar to other language implementations of the same topic.

Once a topic's implementation has been submitted by someone, the topic will be removed from the list or struck.

**Comment by the-cybersapien** [comment]
Hi,
I'd like to help with a few of These. I'll start with the Search Algorithms.

**Comment by VamsiSangam** [comment]
Sure! Do comment if you have any doubts 😄

**Comment by the-cybersapien** [comment]
Do you want these as simple example implementations or as individual classes with JUnit Tests?

**Comment by VamsiSangam** [comment]
Simple example implementations. But make sure your code handles all corner cases. And do comment on which topics you're interested to work so that others can pick the rest.

**Comment by the-cybersapien** [comment]
I'll do the following in Java:
1. Merge Sort
2. Quick Sort Algorithm
3. Binary Search Algorithm
4. Jump Search Algorithm
5. Breadth First Search
6. Depth First Search
7. Dijkstra's Algorithm

I'll see if I can do the rest too, but these I will complete in one or two days.

**Comment by VamsiSangam** [comment]
Sure, work at your own pace. 😄
