### ISSUE TITLE
Implement BFS in Java

### ISSUE THREAD

**Issue by VamsiSangam** [VamsiSangam/theoryofprogramming#25]
### Issue Description
* Need the Java implementation of Breadth First Search algorithm. Please provide a queue based implementation. Use Collections API.
* [Corresponding post on website](http://theoryofprogramming.com/2014/12/25/breadth-first-search-algorithm/)
* Permitted languages - Java

### Guidelines
* Your code will be live on a tutorial website, so code readability and understandability will be given paramount importance.
* Please follow coding conventions listed in [CONVENTIONS.md](https://github.com/VamsiSangam/theoryofprogramming/blob/master/CONVENTIONS.md)
* The directory structure of the project is pretty obvious, but take a moment to go through [STRUCTURE.md](https://github.com/VamsiSangam/theoryofprogramming/blob/master/STRUCTURE.md) if you are confused where to place your code.
* Please add a few sample input output test case files too. Minimum 1. The more the merrier!

**Comment by ranesr** [comment]
@VamsiSangam 

Please, assign this to me.

**Comment by VamsiSangam** [comment]
Sure go ahead!

**Comment by ranesr** [comment]
@VamsiSangam We can close this issue now. Thanks.
