### ISSUE TITLE
Implement Dijkstra's Algorithm in Java

### ISSUE THREAD

**Issue by VamsiSangam** [VamsiSangam/theoryofprogramming#27]
### Issue Description
* Need the Java implementatio of Dijkstra's algorithm. For this issue, please provide the non-optimised O(V^2) implementation.
* [Corresponding post on website](http://theoryofprogramming.com/2015/01/11/dijkstras-algorithm/)
* Permitted languages - Java

### Guidelines
* Your code will be live on a tutorial website, so code readability and understandability will be given paramount importance.
* Please follow coding conventions listed in [CONVENTIONS.md](https://github.com/VamsiSangam/theoryofprogramming/blob/master/CONVENTIONS.md)
* The directory structure of the project is pretty obvious, but take a moment to go through [STRUCTURE.md](https://github.com/VamsiSangam/theoryofprogramming/blob/master/STRUCTURE.md) if you are confused where to place your code.
* Please add a few sample input output test case files too. Minimum 1. The more the merrier!

**Comment by ranesr** [comment]
@VamsiSangam I will work on this.

**Comment by VamsiSangam** [comment]
Sure! Please proceed @ranesr :smile:
