### ISSUE TITLE
Binary Search in C++ - Make vector a local variable

### ISSUE THREAD

**Issue by VamsiSangam** [VamsiSangam/theoryofprogramming#48]
### Issue Description
* For the C++ code in Binary search, vector ```v``` is a global variable. Please make it a local variable and pass it to binary search method as a parameter.
* [Corresponding post on website](http://theoryofprogramming.com/2016/11/04/binary-search-algorithm/)
* Assigned to @salman-bhai 

### Guidelines
* Your code will be live on a tutorial website, so code readability and understandability will be given paramount importance.
* Please follow coding conventions listed in [CONVENTIONS.md](https://github.com/VamsiSangam/theoryofprogramming/blob/master/CONVENTIONS.md)
* The directory structure of the project is pretty obvious, but take a moment to go through [STRUCTURE.md](https://github.com/VamsiSangam/theoryofprogramming/blob/master/STRUCTURE.md) if you are confused where to place your code.
* Please add a few sample input output test case files too. Minimum 1. The more the merrier!

**Comment by sbshah97** [comment]
Shall be done!

**Comment by praveenmylavarapu** [comment]
Why is this issue still open?

**Comment by VamsiSangam** [comment]
Oops! Forgot to close! Thanks for reminding! :smile:
